- link:
    ~/.hammerspoon/init.lua: automation/hammerspoon/init
    ~/.hammerspoon/apps.lua: automation/hammerspoon/apps
    ~/.hammerspoon/Spoons/Lunette.spoon: automation/hammerspoon/Spoons/Lunette.spoon
