- link:
    ~/.zshrc: shells/zsh/zshrc
    ~/.zprofile: shells/zsh/zprofile
    ~/.oh-my-zsh/custom/zsh_function.zsh: shells/zsh/zsh_function
    ~/.oh-my-zsh/custom/zsh_alias.zsh: shells/zsh/zsh_alias
