- defaults:
    link:
      create: true
      relink: true

- clean: [
  "~",
  "~/.config",
  "~/.gnupg",
  "~/.hammerspoon",
  "~/.iterm2",
  "~/.oh-my-zsh"
]

- shell:
    - [git submodule update --init --recursive, Installing submodules]
