# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
export HOMEBREW_NO_ANALYTICS=1

ZSH_THEME="mortalscumbag"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
#ZSH_CUSTOM=~/.zsh_custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  alias-finder
  bazel
  colorize
  direnv
  docker
  docker-compose
  doctl
  git
  gnu-utils
  golang
  gpg-agent
  kubectl
  macos
  pip
  pyenv
  ruby
  rvm
  ssh-agent
  terraform
  tmux
  zsh-syntax-highlighting
)

# shellcheck disable=SC1090,SC1091
source $ZSH/oh-my-zsh.sh

# User configuration

export GEM_HOME=$HOME/.gem
export FLUTTER_HOME=$HOME/repos/flutter
export SSH_KEY_PATH="${HOME}/.ssh/rsa_id"
export GOPATH="${HOME}/.go"
GOROOT="$(brew --prefix golang)/libexec"
export GOROOT
export PATH="$PATH:$HOME/bin:/usr/local/sbin:${GOPATH}/bin:${GOROOT}/bin:$HOME/.rvm/bin:$HOME/.cargo/bin"

activate_gpg
activate_powerline
activate_tmux
activate_rvm
activate_rust

fpath+=~/.zfunc
compinit
