name: Linting
on: push

jobs:
  yaml-lint:
    name: Run yaml linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install yamllint
        run: pip install yamllint==1.24.2
      - name: Run yamllint
        run: yamllint .
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca
        with:
          check_together: "yes"
        env:
          SHELLCHECK_OPTS: -e SC2034 --shell=bash
  shfmt:
    name: Shell format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Install shfmt
        run: GO111MODULE=on go install mvdan.cc/sh/v3/cmd/shfmt@latest
      - name: Check formatting
        run: shfmt -f . | grep -v meta/dotbot | xargs shfmt -s -d
  correct-sha256:
    name: SHA256 in README is correct
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Update SHA script
        run: bin/update-bootstrap-sha
      - name: Check that there is no diff
        run: git diff --exit-code
